import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Teltec',
  description: 'Generated by create next app',
};

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // ou só "400", depende do que você quer usar
  variable: '--font-dm-sans', // opcional, para usar como CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.className}>{children}</body>
    </html>
  );
}
